# Use nvidia/nvhpc as base image
FROM nvcr.io/nvidia/nvhpc:24.7-devel-cuda_multi-ubuntu22.04

# Install of utilities and libraries
RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    unzip \
    vim \
    curl

# Install of Git, OpenSSH, python, pip and make
RUN apt-get update && apt-get install -y git openssh-client make  python3-pip

#install hdf5
WORKDIR /opt
RUN wget https://github.com/HDFGroup/hdf5/releases/download/snapshot/hdf5.tar.gz && \
    tar -xzf hdf5.tar.gz && \
    cd hdf5-1.15.0 && \
    CC=nvc CXX=nvc++ FC=nvfortran F90=nvfortran ./configure \
    --prefix=/opt/hdf5 --enable-fortran --enable-shared \
    CFLAGS="-O3 -fPIC" FFLAGS="-O3 -fPIC" CXXFLAGS="-O3 -fPIC" FCFLAGS="-O3 -fPIC" --host=x86_64-linux-gnu && \
    make -j 8 && \
    make install && \
    rm ../hdf5.tar.gz
