name: dpkg
on:
  workflow_dispatch:
  schedule:
    - cron: "7 0 * * *"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: dpkg
    steps:
      - name: install
        run:  |
          sudo apt-get -q update
          sudo apt install alien
      - name: test
        run:  |
          curl -s -L -O https://github.com/HDFGroup/hdf5/releases/download/snapshot/snapshot-ubuntu-2404_gcc.deb
          sudo dpkg -i snapshot-ubuntu-2404_gcc.deb
          /HDF_Group/HDF5/2.0.1/bin/h5ls --help

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
