name: alma rpm h5cc
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: almalinux:8

    steps:
      - name: verify
        run: |
          cat /etc/redhat-release
          dnf --version

      - name: hdf5
        run: |
          curl -s -L -O https://github.com/HDFGroup/hdf5/releases/download/untagged-2fb73adb9ccacf91b577/hdf5-2.1.0-ubuntu-2404_gcc.rpm
          rpm -i snapshot-ubuntu-2404_gcc.rpm
          ls /HDF_Group/HDF5
          /HDF_Group/HDF5/2.1.0/bin/h5cc -v

