name: clawbernetes

on:
  push:
    branches:
      - main
  workflow_dispatch:      
jobs:
  build:
#    runs-on: windows-2025-vs2026
    runs-on: windows-2025
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          repository: redclawsystems/clawbernetes
      - name: test
        run: |
          npm install -g openclaw@latest
          openclaw onboard --install-daemon
          cargo install --path crates/clawnode

