name: fedora rpm

on:
  push:
    branches: main-

jobs:
  test:
    runs-on: ubuntu-latest
    container: "fedora:latest"
    steps:
      - name: verify
        run: |
          cat /etc/redhat-release
          dnf --version

      - name: install gh
        run: |
          dnf install -y gh

      - name: hdf5
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          gh release download untagged-2fb73adb9ccacf91b577 \
            --repo HDFGroup/hdf5 \
            --pattern "hdf5-2.1.0-ubuntu-2404_gcc.rpm"
          rpm -i hdf5-2.1.0-ubuntu-2404_gcc.rpm
          ls /HDF_Group/HDF5
          /HDF_Group/HDF5/2.1.0/bin/h5cc -v

