name: mac conda

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: iowarp/clio-core
      - name: miniconda
        uses: conda-incubator/setup-miniconda@v4
      - name: iowarp
        run: |
          conda install -y yaml-cpp
          conda config --add channels conda-forge
          conda config --set channel_priority strict
          conda install -y cereal
          conda install -y msgpack-c
          conda install -y zeromq
          conda install -y catch2
          mkdir build
          cd build
          export CONDA_PREFIX=/Users/runner/miniconda3
          cmake -DCMAKE_BUILD_TYPE=Release \
           -DBUILDNAME="r/cnd" \
           -DSITE="mac-15" \
           -DCLIO_CORE_ENABLE_TESTS=ON \
           -DCLIO_CORE_ENABLE_CONDA=ON \
           ..
          ctest -C Release -D Experimental
